### ISSUE TITLE
Replays: Scores repeat when going back and forth between rounds (+ wrong rounds numbers)

### ISSUE THREAD

**Issue by carrdelling** [ApplySci/tenhou-scorepane#1]
This is only an issue when watching replays, and only if you start doing weird things. But in case it helps:

* Currently, the extension adds one score table every time a round ends. This is good, but if you go back after finishing a round and then you continue, things start getting weird:

![image](https://user-images.githubusercontent.com/8481297/90989948-33ca3880-e595-11ea-90bb-1ab335bd1ae9.png)

* Also, if you start a replay from a round that is not the first one, the round numbers are wrong too:

![image](https://user-images.githubusercontent.com/8481297/90989967-670cc780-e595-11ea-84f5-1ec645af291d.png)

(both images are from the same game)

I suspect the current code just keep a counter of how many rounds has seen finishing, instead of reading from the round number from the game data. Maybe if there was an easy way of getting the right round number (can you do that from javascript?), this would solve both issues.

**Comment by ApplySci** [comment]
Yeah, all it does is keep a counter of the hands it's seen. It doesn't read game data, it only reads changes to the DOM. And the round number is written onto a `CANVAS` element, so I haven't seen any way to grab it, yet.

**Comment by ApplySci** [comment]
I'm going to close this now as a WONTFIX (well, actually, CANTFIX), but will come back to it if I do find a way to handle it cleanly.
