### ISSUE TITLE
Doble ron shows as two different rounds

### ISSUE THREAD

**Issue by carrdelling** [ApplySci/tenhou-scorepane#2]
See first round of this game:

https://tenhou.net/3/?log=2020082407gm-0089-0000-bab6ffa6

**Comment by ApplySci** [comment]
I just had the same thing happen to me! It'll need a little trick to deal with this. I'll have a think about it.

**Comment by ApplySci** [comment]
OK, v0.3.1 has been submitted to the Chrome Extension Store, and is already in the Firefox Addons repository. I've added a timer, so that hand number isn't incremented if two wins occur within 20 seconds of each other.
